ALTER TABLE Student
ADD FOREIGN KEY(CourseCode) REFERENCES Course(CourseCode);

ALTER TABLE PQualification
ADD FOREIGN KEY(StudentID) REFERENCES Student(StudentID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Course
ADD FOREIGN KEY(FacultyID) REFERENCES Faculty(FacultyID)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE ALStudent_Subject
ADD FOREIGN KEY(StudentID) REFERENCES Student(StudentID)
ON DELETE CASCADE
ON UPDATE CASCADE,
ADD FOREIGN KEY(SubjectCode) REFERENCES ALSubject(SubjectCode)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE Subject_
ADD FOREIGN KEY(CourseCode) REFERENCES Course(CourseCode)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Enrollment
ADD FOREIGN KEY(StudentID) REFERENCES Student(StudentID)
ON DELETE CASCADE
ON UPDATE CASCADE,
ADD FOREIGN KEY(SubjectCode) REFERENCES Subject_(SubjectCode)
ON DELETE RESTRICT
ON UPDATE CASCADE,
ADD FOREIGN KEY(InvoiceID) REFERENCES Payment(InvoiceID)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE Lecture
ADD FOREIGN KEY(Staff_ID) REFERENCES Lecturer(Staff_ID)
ON DELETE SET NULL
ON UPDATE CASCADE,
ADD FOREIGN KEY(SubjectCode) REFERENCES Subject_(SubjectCode)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Lecturer
ADD FOREIGN KEY(FacultyID) REFERENCES Faculty(FacultyID)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE Assessment
ADD FOREIGN KEY(EnrollmentID) REFERENCES Enrollment(EnrollmentID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE LabSession
ADD FOREIGN KEY(SubjectCode) REFERENCES Subject_(SubjectCode)
ON DELETE CASCADE
ON UPDATE CASCADE,
ADD FOREIGN KEY(LabID) REFERENCES Laboratory(LabID)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE LabSession_Instructor
ADD FOREIGN KEY(LabSessionID) REFERENCES LabSession(LabSessionID)
ON DELETE CASCADE
ON UPDATE CASCADE,
ADD FOREIGN KEY(Staff_ID) REFERENCES Instructor(Staff_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE LabSession_Student
ADD FOREIGN KEY(LabSessionID) REFERENCES LabSession(LabSessionID)
ON DELETE CASCADE
ON UPDATE CASCADE,
ADD FOREIGN KEY(StudentID) REFERENCES Student(StudentID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Instructor AUTO_INCREMENT = 110000;
ALTER TABLE Lecturer AUTO_INCREMENT = 120000;