ALTER TABLE Student
ADD CONSTRAINT fk_course_code FOREIGN KEY(CourseCode) REFERENCES Course(CourseCode);

ALTER TABLE PQualification
ADD CONSTRAINT fk_student_id FOREIGN KEY(StudentID) REFERENCES Student(StudentID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Course
ADD CONSTRAINT fk_faculty_id FOREIGN KEY(FacultyID) REFERENCES Faculty(FacultyID)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE ALStudent_Subject
ADD CONSTRAINT fk_student_id FOREIGN KEY(StudentID) REFERENCES Student(StudentID)
ON DELETE CASCADE
ON UPDATE CASCADE,
ADD CONSTRAINT fk_subject_code FOREIGN KEY(SubjectCode) REFERENCES ALSubject(SubjectCode)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE Subject_
ADD CONSTRAINT fk_course_code FOREIGN KEY(CourseCode) REFERENCES Course(CourseCode)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Enrollment
ADD CONSTRAINT fk_student_id FOREIGN KEY(StudentID) REFERENCES Student(StudentID)
ON DELETE CASCADE
ON UPDATE CASCADE,
ADD CONSTRAINT fk_subject_code FOREIGN KEY(SubjectCode) REFERENCES Subject_(SubjectCode)
ON DELETE RESTRICT
ON UPDATE CASCADE,
ADD CONSTRAINT fk_invoice_id FOREIGN KEY(InvoiceID) REFERENCES Payment(InvoiceID)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE Lecture
ADD CONSTRAINT fk_staff_id FOREIGN KEY(Staff_ID) REFERENCES Lecturer(Staff_ID)
ON DELETE SET NULL
ON UPDATE CASCADE,
ADD CONSTRAINT fk_subject_code FOREIGN KEY(SubjectCode) REFERENCES Subject_(SubjectCode)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Lecturer
ADD CONSTRAINT fk_faculty_id FOREIGN KEY(FacultyID) REFERENCES Faculty(FacultyID)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE Assessment
ADD CONSTRAINT fk_enrollment_id FOREIGN KEY(EnrollmentID) REFERENCES Enrollment(EnrollmentID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE LabSession
ADD CONSTRAINT fk_subject_code FOREIGN KEY(SubjectCode) REFERENCES Subject_(SubjectCode)
ON DELETE CASCADE
ON UPDATE CASCADE,
ADD CONSTRAINT fk_lab_id FOREIGN KEY(LabID) REFERENCES Laboratory(LabID)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE LabSession_Instructor
ADD CONSTRAINT fk_lab_session FOREIGN KEY(LabSessionID) REFERENCES LabSession(LabSessionID)
ON DELETE CASCADE
ON UPDATE CASCADE,
ADD CONSTRAINT fk_staff_id FOREIGN KEY(Staff_ID) REFERENCES Instructor(Staff_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE LabSession_Student
ADD CONSTRAINT fk_lab_session_id FOREIGN KEY(LabSessionID) REFERENCES LabSession(LabSessionID)
ON DELETE CASCADE
ON UPDATE CASCADE,
ADD CONSTRAINT fk_student_id FOREIGN KEY(StudentID) REFERENCES Student(StudentID)
ON DELETE CASCADE
ON UPDATE CASCADE;
